import importlib.util
import os
import sys
import tempfile
import unittest
from pathlib import Path

MODULE = Path(__file__).parents[1] / "deslop.py"
SPEC = importlib.util.spec_from_file_location("deslop_under_test", MODULE)
assert SPEC and SPEC.loader
deslop = importlib.util.module_from_spec(SPEC)
sys.modules["deslop_under_test"] = deslop
SPEC.loader.exec_module(deslop)


def findings(source, language="swift", path="<memory>"):
    return deslop.lint_source(path, source, language)


def rules(source, language="swift", path="<memory>"):
    return {finding.rule for finding in findings(source, language, path)}


class PrecisionTests(unittest.TestCase):
    def test_trailing_annotations_are_not_commented_code(self):
        for source in (
            "encode(1) // protocol tag (1 = primary)\n",
            "columns * 2 // rows = 2\n",
            "case 3: // RGB (12-bit)\n",
        ):
            self.assertNotIn("commented-out-code", rules(source, "kotlin"))

    def test_trailing_residue_still_fires(self):
        self.assertIn("notes-to-self", rules("let x = 1 // as requested\n"))

    def test_prose_parentheticals_are_not_calls(self):
        self.assertNotIn("commented-out-code", rules("// Cache (encrypted storage)\nlet x = 1\n"))
        self.assertIn("commented-out-code", rules("// refreshCache()\nlet x = 1\n"))
        self.assertIn("commented-out-code", rules("// doWork (value);\nlet x = 1\n"))

    def test_prose_mapping_is_not_assignment_but_multi_assignment_is(self):
        text = "// Disabled = omit field, Enabled = include field\nlet x = 1\n"
        self.assertNotIn("commented-out-code", rules(text, "kotlin"))
        self.assertIn("commented-out-code", rules("// let x = foo(), y = bar()\nlet z = 1\n", "kotlin"))
        self.assertIn("commented-out-code", rules("// x = 1, y = 2\nlet z = 1\n", "kotlin"))

    def test_generated_files_are_skipped(self):
        source = "// Generated by tool\n// Add refresh handler\nrefreshHandler.register()\n"
        self.assertEqual([], findings(source, path="src/Generated/File.swift"))
        self.assertEqual([], findings(source, path="src/GeneratedByHand/File.swift"))
        manual = "// Add refresh handler\nrefreshHandler.register()\n"
        self.assertIn("narration", rules(manual, path="src/GeneratedByHand/File.swift"))

    def test_generated_marker_inside_string_does_not_skip_file(self):
        source = 'const marker = "DO NOT EDIT"\n// as requested\nconst value = 1\n'
        self.assertIn("notes-to-self", rules(source, "javascript", "src/a.js"))

    def test_swift_extended_raw_strings_are_ignored(self):
        for source in (
            'let value = ##"""\n// as requested\n"""##\n',
            "let regex = ##/\n// as requested\n/##\n",
        ):
            self.assertEqual(set(), rules(source))

    def test_fenced_doc_examples_are_ignored_by_every_rule(self):
        for fence in ("```", "~~~"):
            with self.subTest(fence=fence):
                source = (
                    f"/**\n * Example:\n * {fence}swift\n * Analytics()\n"
                    f" * as requested\n * Step 1: Add widget\n"
                    f" * Add widget\n * {fence}\n */\n"
                    "widgets.append(widget)\n"
                )
                self.assertEqual(set(), rules(source))

    def test_fenced_line_comment_examples_are_ignored_by_every_rule(self):
        for prefix in ("//", "///"):
            for fence in ("```", "~~~"):
                with self.subTest(prefix=prefix, fence=fence):
                    source = (
                        f"{prefix} Example:\n{prefix} {fence}go\n"
                        f"{prefix} value := load()\n{prefix} as requested\n"
                        f"{prefix} Step 1: Add widget\n"
                        f"{prefix} Add widget\n{prefix} {fence}\n"
                        "widgets.append(widget)\n"
                    )
                    self.assertEqual(set(), rules(source, "go"))

    def test_rules_resume_after_a_line_comment_fence(self):
        source = "// ```\n// ignored()\n// ```\n// staleCall()\n"
        self.assertIn("commented-out-code", rules(source))

    def test_block_narration_looks_after_the_entire_comment(self):
        unrelated = "/**\n * Add widget\n */\nlet count = 1\n"
        self.assertNotIn("narration", rules(unrelated))
        restatement = "/**\n * Add widget\n */\nwidgets.append(widget)\n"
        self.assertIn("narration", rules(restatement))

    def test_numbered_steps_and_narration_are_deterministic(self):
        self.assertIn("step-scaffold", rules("// Step 1: Download file\ndownload()\n"))
        self.assertNotIn("step-scaffold", rules("// Step 2 of the handshake retries.\nretry()\n"))
        self.assertIn("narration", rules("// Add refresh handler\nrefreshHandler.register()\n"))
        self.assertNotIn("narration", rules("// Add listener to avoid duplicate callbacks\naddListener()\n"))

    def test_supported_language_set_is_preserved(self):
        paths = (
            "a.rs", "a.java", "a.c", "a.cpp", "a.rb", "a.sh",
            "a.yaml", "a.sql", "a.lua",
        )
        for path in paths:
            with self.subTest(path=path):
                self.assertIsNotNone(deslop.language_for_path(path))

    def test_type_comments_and_scala_cli_directives_are_exempt(self):
        self.assertNotIn("commented-out-code", rules("# type: Result\n", "python"))
        self.assertNotIn("commented-out-code", rules("//> using scala 3.3.1\n", "scala"))

    def test_source_reader_rejects_symlinks_and_oversized_files(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            target = root / "target.py"
            target.write_text("# safe\n", encoding="utf-8")
            link = root / "link.py"
            os.symlink(target, link)
            with self.assertRaises(OSError):
                deslop._read_source(link)

            large = root / "large.py"
            with large.open("wb") as stream:
                stream.truncate(deslop._MAX_SOURCE_BYTES + 1)
            with self.assertRaises(OSError):
                deslop._read_source(large)


class BlockCommentTests(unittest.TestCase):
    def test_interior_finding_uses_its_physical_line(self):
        source = "/* heading\n * ordinary prose\n * as requested, remove this\n */\nlet x = 1\n"
        result = findings(source)
        residue = next(item for item in result if item.rule == "notes-to-self")
        self.assertEqual(3, residue.line)

    def test_nested_blocks_do_not_end_outer_comment(self):
        source = "/* outer\n /* nested */\n as requested\n*/\nlet x = 1\n"
        for language in ("swift", "kotlin", "scala", "rust"):
            with self.subTest(language=language):
                result = findings(source, language)
                residue = next(item for item in result if item.rule == "notes-to-self")
                self.assertEqual(3, residue.line)

    def test_trailing_block_only_suppresses_its_mixed_opener_line(self):
        source = "run(); /* explanation\n * oldCall()\n */\n"
        result = findings(source)
        commented_code = next(item for item in result if item.rule == "commented-out-code")
        self.assertEqual(2, commented_code.line)


class DiffTests(unittest.TestCase):
    def test_added_increment_is_not_mistaken_for_file_header(self):
        diff = (
            "diff --git a/a.ts b/a.ts\n"
            "--- a/a.ts\n"
            "+++ b/a.ts\n"
            "@@ -1 +1,3 @@\n"
            " const a = 1;\n"
            "+++n;\n"
            "+// as requested\n"
        )
        self.assertEqual({"a.ts": {2, 3}}, deslop.added_lines(diff))

    def test_quoted_path_is_skipped_instead_of_opened_literally(self):
        diff = (
            'diff --git "a/\\303\\251.ts" "b/\\303\\251.ts"\n'
            '--- "a/\\303\\251.ts"\n'
            '+++ "b/\\303\\251.ts"\n'
            "@@ -0,0 +1 @@\n"
            "+// as requested\n"
        )
        self.assertEqual({}, deslop.added_lines(diff))


class BodyLintTests(unittest.TestCase):
    def test_lints_body_without_host_template_assumptions(self):
        body = (
            "## Summary\n\n<!-- TODO: explain why -->\n"
            "Adds a comprehensive and seamless fix.\n"
            "## Testing\n\n- [ ] run unit tests\n- [ ] test manually\n"
        )
        found = {item.rule for item in deslop.lint_body(body)}
        self.assertTrue({"template-debris", "filler-adjective", "unchecked-checklist"} <= found)

    def test_ignores_fenced_and_inline_examples(self):
        body = (
            "## Summary\n\nDiscusses `comprehensive` as a banned example.\n"
            "```markdown\n<!-- TODO: placeholder -->\nSimply do it.\n```\n"
        )
        self.assertEqual([], deslop.lint_body(body))

    def test_flags_residue_and_politeness(self):
        found = {item.rule for item in deslop.lint_body(
            "As discussed, this changes retries.\nPlease note that rollout is manual.\n"
        )}
        self.assertEqual({"notes-to-self", "politeness"}, found)


if __name__ == "__main__":
    unittest.main()
