import importlib.util
import os
import sys
import tempfile
import unittest
from pathlib import Path

MODULE = Path(__file__).parents[1] / "deslop.py"
SPEC = importlib.util.spec_from_file_location("deslop_under_test", MODULE)
assert SPEC and SPEC.loader
deslop = importlib.util.module_from_spec(SPEC)
sys.modules["deslop_under_test"] = deslop
SPEC.loader.exec_module(deslop)


def findings(source, language="swift", path="<memory>"):
    return deslop.lint_source(path, source, language)


def rules(source, language="swift", path="<memory>"):
    return {finding.rule for finding in findings(source, language, path)}


class PrecisionTests(unittest.TestCase):
    def test_trailing_annotations_are_not_commented_code(self):
        for source in (
            "encode(1) // protocol tag (1 = primary)\n",
            "columns * 2 // rows = 2\n",
            "case 3: // RGB (12-bit)\n",
        ):
            self.assertNotIn("commented-out-code", rules(source, "kotlin"))

    def test_trailing_residue_still_fires(self):
        self.assertIn("notes-to-self", rules("let x = 1 // as requested\n"))

    def test_prose_parentheticals_are_not_calls(self):
        self.assertNotIn("commented-out-code", rules("// Cache (encrypted storage)\nlet x = 1\n"))
        self.assertIn("commented-out-code", rules("// refreshCache()\nlet x = 1\n"))
        self.assertIn("commented-out-code", rules("// doWork (value);\nlet x = 1\n"))

    def test_prose_mapping_is_not_assignment_but_multi_assignment_is(self):
        text = "// Disabled = omit field, Enabled = include field\nlet x = 1\n"
        self.assertNotIn("commented-out-code", rules(text, "kotlin"))
        self.assertIn("commented-out-code", rules("// let x = foo(), y = bar()\nlet z = 1\n", "kotlin"))
        self.assertIn("commented-out-code", rules("// x = 1, y = 2\nlet z = 1\n", "kotlin"))

    def test_generated_files_are_skipped(self):
        source = "// Generated by tool\n// Add refresh handler\nrefreshHandler.register()\n"
        self.assertEqual([], findings(source, path="src/Generated/File.swift"))
        self.assertEqual([], findings(source, path="src/GeneratedByHand/File.swift"))
        licensed = (
            "// Copyright 2026 Example\n// Generated by tool\n"
            "// Add refresh handler\nrefreshHandler.register()\n"
        )
        self.assertEqual([], findings(licensed, path="src/File.swift"))
        manual = "// Add refresh handler\nrefreshHandler.register()\n"
        self.assertIn("narration", rules(manual, path="src/GeneratedByHand/File.swift"))

    def test_generated_marker_inside_string_does_not_skip_file(self):
        source = 'const marker = "DO NOT EDIT"\n// as requested\nconst value = 1\n'
        self.assertIn("notes-to-self", rules(source, "javascript", "src/a.js"))

    def test_generated_phrase_requires_a_header_marker(self):
        source = "// IDs are generated by the backend\n// as requested\nconst value = 1\n"
        self.assertIn("notes-to-self", rules(source, "javascript", "src/a.js"))
        block = (
            "/* Header\n * Generated by the backend\n */\n"
            "// as requested\nconst value = 1\n"
        )
        self.assertIn("notes-to-self", rules(block, "javascript", "src/a.js"))
        local = "const value = 1\n\n// Generated by helper\n// as requested\n"
        self.assertIn("notes-to-self", rules(local, "javascript", "src/a.js"))
        trailing = "const value = 1; // Generated by helper\n// as requested\n"
        self.assertIn("notes-to-self", rules(trailing, "javascript", "src/a.js"))

    def test_javascript_regex_literals_do_not_open_comments(self):
        for source in (
            "const pattern = /[//] as requested/;\nconst value = 1;\n",
            "return /https?:\\/\\//.test(value);\n",
            "const pattern = await /[//]/;\n",
            "const matches = value => /[//]/.test(value);\n",
            "if (enabled) /[//]/.test(value);\n",
            "for (let i = 0; i < n; i++) /[//]/.test(value);\n",
            "const pattern = typeof /[//]/;\n",
        ):
            with self.subTest(source=source):
                self.assertNotIn("notes-to-self", rules(source, "javascript", "src/a.js"))
        trailing = "const pattern = /[//]/; // as requested\n"
        self.assertIn("notes-to-self", rules(trailing, "javascript", "src/a.js"))
        line_division = "numerator\n/ denominator // as requested\n"
        self.assertIn("notes-to-self", rules(line_division, "javascript", "src/a.js"))
        for division in (
            "if (enabled) calculate() / denominator // as requested\n",
            "object.do / denominator // as requested\n",
        ):
            with self.subTest(division=division):
                self.assertIn("notes-to-self", rules(division, "javascript", "src/a.js"))

    def test_swift_extended_raw_strings_are_ignored(self):
        for source in (
            'let value = ##"""\n// as requested\n"""##\n',
            "let regex = ##/\n// as requested\n/##\n",
        ):
            self.assertEqual(set(), rules(source))

    def test_raw_strings_do_not_swallow_following_comments(self):
        # Kotlin/Scala/Java """ and Go ` literals take no escapes and may hold an
        # odd number of quotes; the comment after each must still be seen.
        for language, path, source in (
            ("kotlin", "a.kt", 'val s = """a"b"""\n// per your feedback\nval x = 1\n'),
            ("kotlin", "a.kt", 'val p = """C:\\"""\n// per your feedback\nval x = 1\n'),
            ("kotlin", "a.kt", 'val t = """a""""\n// per your feedback\nval x = 1\n'),
            ("scala", "a.scala", 'val q = """where n = \'x\' and m = "y"""\n// per your feedback\nval x = 1\n'),
            ("java", "A.java", 'String s = """\n  {"k": "v"}\n  """;\n// per your feedback\nint x = 1;\n'),
            ("go", "a.go", 'p := `C:\\`\n// per your feedback\nvar x = 1\n'),
        ):
            with self.subTest(language=language, source=source):
                self.assertIn("notes-to-self", rules(source, language, path))
        # A `//` inside the raw literal is string content, not a comment.
        self.assertEqual(set(), rules('val u = """http://x"""\n', "kotlin", "a.kt"))
        self.assertEqual(set(), rules("u := `http://x`\n", "go", "a.go"))

    def test_fenced_doc_examples_are_ignored_by_every_rule(self):
        for fence in ("```", "~~~"):
            with self.subTest(fence=fence):
                source = (
                    f"/**\n * Example:\n * {fence}swift\n * Analytics()\n"
                    f" * as requested\n * Step 1: Add widget\n"
                    f" * Add widget\n * {fence}\n */\n"
                    "widgets.append(widget)\n"
                )
                self.assertEqual(set(), rules(source))

    def test_fenced_line_comment_examples_are_ignored_by_every_rule(self):
        for prefix in ("//", "///"):
            for fence in ("```", "~~~"):
                with self.subTest(prefix=prefix, fence=fence):
                    source = (
                        f"{prefix} Example:\n{prefix} {fence}go\n"
                        f"{prefix} value := load()\n{prefix} as requested\n"
                        f"{prefix} Step 1: Add widget\n"
                        f"{prefix} Add widget\n{prefix} {fence}\n"
                        "widgets.append(widget)\n"
                    )
                    self.assertEqual(set(), rules(source, "go"))

    def test_fence_closer_matches_character_and_minimum_length(self):
        source = (
            "// ````markdown\n// ```\n// as requested\n// ```\n// ````\n"
            "// ~~~~markdown\n// ```\n// as requested\n// ~~~\n// ~~~~\n"
            "let value = 1\n"
        )
        self.assertEqual(set(), rules(source))

    def test_four_space_indented_markers_are_not_fences(self):
        line_comment = "//     ```\n// as requested\n//     ```\n"
        self.assertIn("notes-to-self", rules(line_comment))
        block_comment = "/**\n *     ```\n * as requested\n *     ```\n */\n"
        self.assertIn("notes-to-self", rules(block_comment))

    def test_every_rule_resumes_after_a_line_comment_fence(self):
        source = (
            "// ```\n// ignored()\n// ```\n"
            "// as requested\n// Step 1: Add widget\n// Add widget\n"
            "widgets.append(widget)\n// staleCall()\n"
        )
        self.assertEqual(
            {"notes-to-self", "step-scaffold", "narration", "commented-out-code"},
            rules(source),
        )

    def test_block_narration_looks_after_the_entire_comment(self):
        unrelated = "/**\n * Add widget\n */\nlet count = 1\n"
        self.assertNotIn("narration", rules(unrelated))
        restatement = "/**\n * Add widget\n */\nwidgets.append(widget)\n"
        self.assertIn("narration", rules(restatement))

    def test_numbered_steps_and_narration_are_deterministic(self):
        self.assertIn("step-scaffold", rules("// Step 1: Download file\ndownload()\n"))
        self.assertNotIn("step-scaffold", rules("// Step 2 of the handshake retries.\nretry()\n"))
        self.assertIn("narration", rules("// Add refresh handler\nrefreshHandler.register()\n"))
        self.assertNotIn("narration", rules("// Add listener to avoid duplicate callbacks\naddListener()\n"))

    def test_supported_language_set_is_preserved(self):
        paths = (
            "a.rs", "a.java", "a.c", "a.cpp", "a.rb", "a.sh",
            "a.yaml", "a.sql", "a.lua",
        )
        for path in paths:
            with self.subTest(path=path):
                self.assertIsNotNone(deslop.language_for_path(path))

    def test_type_comments_and_scala_cli_directives_are_exempt(self):
        self.assertNotIn("commented-out-code", rules("# type: Result\n", "python"))
        self.assertNotIn("commented-out-code", rules("//> using scala 3.3.1\n", "scala"))

    def test_source_reader_rejects_symlinks_and_oversized_files(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            target = root / "target.py"
            target.write_text("# safe\n", encoding="utf-8")
            link = root / "link.py"
            os.symlink(target, link)
            with self.assertRaises(OSError):
                deslop._read_source(link)

            large = root / "large.py"
            with large.open("wb") as stream:
                stream.truncate(deslop._MAX_SOURCE_BYTES + 1)
            with self.assertRaises(OSError):
                deslop._read_source(large)


class BlockCommentTests(unittest.TestCase):
    def test_interior_finding_uses_its_physical_line(self):
        source = "/* heading\n * ordinary prose\n * as requested, remove this\n */\nlet x = 1\n"
        result = findings(source)
        residue = next(item for item in result if item.rule == "notes-to-self")
        self.assertEqual(3, residue.line)

    def test_nested_blocks_do_not_end_outer_comment(self):
        source = "/* outer\n /* nested */\n as requested\n*/\nlet x = 1\n"
        for language in ("swift", "kotlin", "scala", "rust"):
            with self.subTest(language=language):
                result = findings(source, language)
                residue = next(item for item in result if item.rule == "notes-to-self")
                self.assertEqual(3, residue.line)

    def test_trailing_block_only_suppresses_its_mixed_opener_line(self):
        source = "run(); /* explanation\n * oldCall()\n */\n"
        result = findings(source)
        commented_code = next(item for item in result if item.rule == "commented-out-code")
        self.assertEqual(2, commented_code.line)


class DiffTests(unittest.TestCase):
    def test_added_increment_is_not_mistaken_for_file_header(self):
        diff = (
            "diff --git a/a.ts b/a.ts\n"
            "--- a/a.ts\n"
            "+++ b/a.ts\n"
            "@@ -1 +1,3 @@\n"
            " const a = 1;\n"
            "+++n;\n"
            "+// as requested\n"
        )
        self.assertEqual({"a.ts": {2, 3}}, deslop.added_lines(diff))

    def test_quoted_path_is_skipped_instead_of_opened_literally(self):
        diff = (
            'diff --git "a/\\303\\251.ts" "b/\\303\\251.ts"\n'
            '--- "a/\\303\\251.ts"\n'
            '+++ "b/\\303\\251.ts"\n'
            "@@ -0,0 +1 @@\n"
            "+// as requested\n"
        )
        self.assertEqual({}, deslop.added_lines(diff))


class BodyLintTests(unittest.TestCase):
    def test_lints_body_without_host_template_assumptions(self):
        body = (
            "## Summary\n\n<!-- TODO: explain why -->\n"
            "Adds a comprehensive and seamless fix.\n"
            "## Testing\n\n- [ ] run unit tests\n- [ ] test manually\n"
        )
        found = {item.rule for item in deslop.lint_body(body)}
        self.assertTrue({"template-debris", "filler-adjective", "unchecked-checklist"} <= found)

    def test_ignores_fenced_and_inline_examples(self):
        body = (
            "## Summary\n\nDiscusses `comprehensive` as a banned example.\n"
            "````markdown\n```\n<!-- TODO: placeholder -->\nSimply do it.\n```\n````\n"
            "~~~~markdown\n```\nAs discussed, retry.\n~~~\n~~~~\n"
        )
        self.assertEqual([], deslop.lint_body(body))

    def test_four_space_indented_body_marker_is_not_a_fence(self):
        body = "    ```\nAs discussed, retry.\n    ```\n"
        self.assertIn("notes-to-self", {item.rule for item in deslop.lint_body(body)})

    def test_flags_residue_and_politeness(self):
        found = {item.rule for item in deslop.lint_body(
            "As discussed, this changes retries.\nPlease note that rollout is manual.\n"
        )}
        self.assertEqual({"notes-to-self", "politeness"}, found)

    def test_discussion_exemption_requires_a_durable_reference(self):
        conversational = deslop.lint_body("As discussed in our conversation, retry.\n")
        self.assertIn("notes-to-self", {item.rule for item in conversational})
        for reference in (
            "#123",
            "issue #123",
            "SDK-42",
            "owner/repo#123",
            "docs/retries.md",
            "[the design](https://example.com/design)",
            "https://example.com/design",
        ):
            with self.subTest(reference=reference):
                self.assertNotIn(
                    "notes-to-self",
                    {item.rule for item in deslop.lint_body(
                        f"As discussed in {reference}, retry.\n"
                    )},
                )


if __name__ == "__main__":
    unittest.main()
